from __future__ import annotations

import xml.etree.ElementTree as ET
from xml.dom import minidom

from ce_base_extractor.export.formatter import format_ce_table
from ce_base_extractor.models import ExtractResult, PointerChain

_CT_TYPE_MAP = {
    "int8": "Byte",
    "uint8": "Byte",
    "byte": "Byte",
    "int16": "2 Bytes",
    "uint16": "2 Bytes",
    "int32": "4 Bytes",
    "uint32": "4 Bytes",
    "int64": "8 Bytes",
    "uint64": "8 Bytes",
    "float": "Float",
    "double": "Double",
}


def _ct_variable_type(value_type: str) -> str:
    return _CT_TYPE_MAP.get(value_type.lower(), "4 Bytes")


def _prettify(elem: ET.Element) -> str:
    rough = ET.tostring(elem, encoding="unicode")
    parsed = minidom.parseString(rough)
    return parsed.toprettyxml(indent="  ", encoding="utf-8").decode("utf-8")


def chains_to_ct(
    chains: list[PointerChain],
    title: str = "CE Base Extractor",
    description: str = "",
) -> str:
    root = ET.Element("CheatTable")
    ET.SubElement(root, "CheatEntries")

    meta = ET.SubElement(root, "UserdefinedSymbols")
    meta.attrib["Count"] = "0"

    desc = ET.SubElement(root, "Comments")
    desc.text = description or "Generated by ce-base-extractor"

    entries_parent = root.find("CheatEntries")
    assert entries_parent is not None

    for i, chain in enumerate(chains, 1):
        entry = ET.SubElement(entries_parent, "CheatEntry")
        ET.SubElement(entry, "ID").text = str(i)
        ET.SubElement(entry, "Description").text = f"{chain.module_name}+0x{chain.module_offset:X}"
        ET.SubElement(entry, "VariableType").text = _ct_variable_type(chain.value_type)
        ET.SubElement(entry, "Address").text = format_ce_table(chain)

    cheat_table = ET.SubElement(root, "CheatTableMeta")
    ET.SubElement(cheat_table, "Title").text = title

    return _prettify(root)


def result_to_ct(result: ExtractResult, title: str = "CE Base Extractor") -> str:
    return chains_to_ct(result.chains, title=title, description=result.source_file)
